// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5y_ctCn2AYOqWXHxF943fJ2mG2HwPXJo',
    appId: '1:900366558058:web:f0dcb6c0ab77dc9b5cfb13',
    messagingSenderId: '900366558058',
    projectId: 'flutter-reddit-31843',
    authDomain: 'flutter-reddit-31843.firebaseapp.com',
    storageBucket: 'flutter-reddit-31843.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw03Is0dyslWvTLW5bQckFL_IWIrfsJ-8',
    appId: '1:900366558058:android:251e95255279fa6c5cfb13',
    messagingSenderId: '900366558058',
    projectId: 'flutter-reddit-31843',
    storageBucket: 'flutter-reddit-31843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNAWyvIJzKpBNfwSl2A_2bwClsZ88Pzzc',
    appId: '1:900366558058:ios:ac53646b136e44695cfb13',
    messagingSenderId: '900366558058',
    projectId: 'flutter-reddit-31843',
    storageBucket: 'flutter-reddit-31843.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNAWyvIJzKpBNfwSl2A_2bwClsZ88Pzzc',
    appId: '1:900366558058:ios:1f9bcb13a63a25db5cfb13',
    messagingSenderId: '900366558058',
    projectId: 'flutter-reddit-31843',
    storageBucket: 'flutter-reddit-31843.appspot.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
